baseurl = "http://reformeddeacon.com/"
languageCode = "en-us"
title = "Readings in the Reformed Diaconate"
[taxonomies]
  author = "authors"
  tag = "tags"
  source = "source"
[params]
  simpleurl = "ReformedDeacon.com"
